bases:
- ../../base

patches:
 - replicas.yaml

configMapGenerator:
- name: mykustom-map
  env: config.properties
resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: kustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1
